version: '3'

services:
  ghost:
    image: amouat/ghost-docker:latest
    volumes: 
      - ./config.js:/var/lib/ghost/config.js
      - ghost_data:/var/lib/ghost
  nginx:
    image: nginx:1.13-alpine
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
#      - /data/letsencrypt-www:/tmp/letsencrypt
#      - /data/letsencrypt:/etc/letsencrypt
    ports: 
      - "80:80"
#     - "443:443"


