version: '3'

services:
  ghost:
    image: amouat/ghost
    volumes: 
      - ./config.js:/var/lib/ghost/config.js
  nginx:
    image: nginx:1.13-alpine
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "80:80"


